name: blaze_sdk_flutter
description: "SDK for integrating Breeze 1CCO into your Cross platform Flutter Application"
version: 0.0.1
homepage: https://breeze.in

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: in.breeze.blaze_sdk_flutter
        pluginClass: BlazeSdkFlutterPlugin
      ios:
        pluginClass: BlazeSdkFlutterPlugin
      web:
        pluginClass: BlazeSdkFlutterWeb
        fileName: blaze_sdk_flutter_web.dart
